### ISSUE TITLE
cant install libreoffice theme with script on osx

### ISSUE THREAD

**Issue by muzirian** [dracula/libreoffice#11]
install.sh on osx is fails with
`Copying palette to config directory ...
cp: directory /Users/myname/.config/libreoffice/*/user/config does not exist
Running add-dracula-application-colors.sh ...
./add-dracula-application-colors.sh: line 7: Support/LibreOffice/*/user/config/: No such file or directory
realpath: missing operand
Try 'realpath --help' for more information.
cp: : No such file or directory
Settings file doesn't exist in expected location. Aborting ...
`

add-dracula-application-colors.sh fails with
`add-dracula-application-colors.sh: line 7: Support/LibreOffice/*/user/config/: No such file or directory
realpath: missing operand
Try 'realpath --help' for more information.
cp: : No such file or directory
Settings file doesn't exist in expected location. Aborting ...`

**Comment by KeshariPiyush24** [comment]
faced the same issue. Solved the path not found issue but then got `Settings file doesn't exist in expected location. Aborting ...` issue :(

**Comment by eleanor-clifford** [comment]
just pushed a commit which might fix it, can you try?

I can't actually test on macos, which makes this harder to sort lol (I'm also very short on time nowadays :/ )

**Comment by eleanor-clifford** [comment]
I've just pushed another commit which hopefully will make it work this time, let's see.

**Comment by fugueink** [comment]
Still not working, I'm afraid. . . .

```
libreoffice-master % cp /<my user folder>/Library/Application\ Support/LibreOffice/4/user/config/libreoffice-master/dracula.soc <my user folder>/Library/Application\ Support/LibreOffice/4/user/config
 libreoffice-master % /<my user folder>/Library/Application\ Support/LibreOffice/4/user/config/libreoffice-master/install.sh
Copying palette to config directory ...
cp: directory /<my user folder>/.config/libreoffice/*/user/config does not exist
Running add-dracula-application-colors.sh ...
grep: <my user folder>/Library/Application: No such file or directory
grep: Support/LibreOffice/4/user/registrymodifications.xcu: No such file or directory
head: illegal line count -- -1

```

**Comment by eleanor-clifford** [comment]
pushed a change fixing those errors, let's see if there are more...

this would be easier if I could test the changes directly but oh well, Apple's proprietary nature strikes again  :(

**Comment by fugueink** [comment]
Actually, I think I may have done something. The error looks odd, considering I dragged and dropped.

```
libreoffice-master % sudo /<my user folder>/Library/Application\ Support/LibreOffice/4/user/config/libreoffice-master/install.sh
sudo: /<my user folder>/Library/Application Support/LibreOffice/4/user/config/libreoffice-master/install.sh: command not found
```

Sorry about Apple . . .

**Comment by eleanor-clifford** [comment]
looks like you probably accidentally deleted the script or moved it somewhere else -- if not that's a very confusing error

**Comment by fugueink** [comment]
But I dragged and dropped the icon into Terminal. How could it possibly not be present?

**Comment by fugueink** [comment]
Okay, I took it all out and reinstalled.

Everything seemed to run okay, no error messages, but . . . it doesn't seem to work.

I went in and chose Dracula in Application Colors, but this is what a new text document looks like.

![Screen Shot 2023-04-08 at 4 39 21 PM](https://user-images.githubusercontent.com/1401986/230741820-640800fa-c392-479b-89fe-70b13ff1a466.png)

On edit:
Just in case it's useful, here's what Terminal showed:

```
libreoffice-master % cp /<my user folder>/Library/Application\ Support/LibreOffice/4/user/config/libreoffice-master/dracula.soc /<my user folder>/Library/Application\ Support/LibreOffice/4/user/config 
libreoffice-master % /<my user folder>/Library/Application\ Support/LibreOffice/4/user/config/libreoffice-master/install.sh
Copying palette to config directory ...
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
Running add-dracula-application-colors.sh ...
libreoffice-master % 

```

**Comment by eleanor-clifford** [comment]
Seems to be working, was the background of a new page not dracula theme before? If i remember correctly the UI colors are out of scope of this theme. On Linux, you can set those with the [GTK Theme](https://draculatheme.com/gtk). Not sure about macOS

**Comment by fugueink** [comment]
Well, I am kinda baffled. I mean, LibreOffice Dark did that much. I thought the point of Dracula was the whole to do that.

My mistake.

I guess I'll have to see if I can find a way to make GTK Theme work.

Thank you!
