### ISSUE TITLE
Install instructions don't work on LO 4 (macOS)

### ISSUE THREAD

**Issue by ghost** [dracula/libreoffice#2]
Following the instructions for macOS, after restarting LO there is still only the default theme under Application Colors.

Is there a new location to put the theme?

Also, does this skin the entire application or just the document itself?

**Comment by ktnk-dev** [comment]
same

**Comment by eleanor-clifford** [comment]
This theme only provides a color palette at the moment, but I'll look into adding application colors.

See #3 for the continuation of this issue
